# SearXNG settings, before editing this file read:
#
#     https://docs.searxng.org/admin/engines/settings.html

use_default_settings: true

general:
  # Debug mode, only for development
  debug: false


search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 1

  # Default search language - leave blank to detect from browser information or
  # use codes from 'languages.py'
  default_lang: 'all'

  # remove format to deny access, use lower case.
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey"  # change this!
  
  # Proxying image results through SearXNG
  image_proxy: false

